### ISSUE TITLE
Add-on not available on  splubkbase

### ISSUE THREAD

**Issue by revnav** [oracle-quickstart/oci-arch-logging-splunk#1]
Going to add-on on splunkbase: https://splunkbase.splunk.com/app/5222/
it  asks you to contact support to get the add-on. Opening SR we get this reply...

"Thank you for your patience as we continued to look into this. I do apologize for the prolonged wait. I was able to connect with one of our Solutions Architects and they confirmed that this tool actually isn't supported/available yet for integration. There are ongoing conversations to expedite this but there isn't currently a target date yet for this to be available."

Any  idea when add-on will be made available?

**Comment by KartikShrikantHegde** [comment]
Hello,

The plugin is now available.  If you still have your SR open, please inquire and our virtual networking product management will be able to provide you one. Otherwise if you open new SR, they will be able to assist you as well.

Thanks,
Kartik

**Comment by lgodoys** [comment]
Add-on is not available again. Shows as "archived" in Splunkbase, and, there is no option to download and/or install in a Splunk environment (standalone, distributed or clustered). There is no step-by-step on how to install in a clustered environment, which roles require the add-on.

**Comment by Halimer** [comment]
Updated guide includes a download link under the OCI Configuration Splunk Plugin Installation and Setup section.
