### ISSUE TITLE
Guide does not work with latest version of the add-on

### ISSUE THREAD

**Issue by mo-504** [oracle-quickstart/oci-arch-logging-splunk#2]
Trying to get the latest version of the add-on (1.1.0) to work.
I am having trouble figuring where to place the pem file.

I have pasted a full path in the add-on settings:

![image](https://user-images.githubusercontent.com/514482/118930459-577dac00-b978-11eb-9835-96b2aa5e275b.png)

But the add-on always complained about "Not a private key / incorrect passphrase" error

![image](https://user-images.githubusercontent.com/514482/118930611-8c89fe80-b978-11eb-9425-69df7ae62480.png)

Any idea on what is wrong or any place to check for log?

Any plan to update the guide to reflect changes in the latest version of the add-on?

**Comment by Halimer** [comment]
The guide has been updated.  Thank you for your feedback.
